name: QMK Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Asume que tu repositorio es un 'fork' del firmware de QMK
    # Si tu keymap está en un 'user space' separado, los pasos cambiarían un poco
    
    steps:
      - name: Checkout QMK Firmware (con submódulos)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup QMK
        uses: qmk/setup-qmk@v1

      - name: Compile Firmware
        run: |
          qmk compile -j$(nproc) -kb bastardkb/charybdis/3x5/v2/splinky_3 -km default

      - name: Upload compiled firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: charybdis-firmware
          path: ./*.uf2
