name: QMK Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install QMK dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qmk

      - name: Set up QMK
        run: |
          qmk setup -y
          qmk doctor

      - name: Compile firmware
        run: |
          qmk compile -kb bastardkb/charybdis/3x5/v2/splinky_3 -km default

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: compiled_firmware
          path: |
            *.uf2

